### ISSUE TITLE
Doesn't seem to work now (Win 10 / Firefox 77)

### ISSUE THREAD

**Issue by RiteshSingh** [skygate2012/i_would_like_to_obtain_a_sample_plox#2] opened 2020-06-16 07:54 UTC
Thank you for your effort.

But this doesn't seem to work now.

**Comment by skygate2012** [comment] 2020-06-16 09:20
Duplicate of #1 
Please use Firefox 68.9.0esr, I haven't found a way to solve this issue yet.

**Closed as completed by skygate2012** 2020-06-16 09:20 UTC

**Comment by RiteshSingh** [comment] 2020-06-16 11:59
Update: **Works in Firefox 70.0.1**

Thank you!!
